// TYPES OF TEXT IF I TAKE A MISTAKE IN WRITING I FOUND IT FAST
export const IS_SEND_LOADING        = "IS_SEND_LOADING"
export const IS_SEND_FAILED_LOADING = "IS_SEND_FAILED_LOADING"
export const IS_SEND_LOADED         = "IS_SEND_LOADED"
export const OPEN_AUTH             	= "OPEN_AUTH"
export const CLOSE_AUTH           	= "CLOSE_AUTH"
export const OPEN_WINDOW            = "OPEN_WINDOW"
export const CLOSE_WINDOW          	= "CLOSE_WINDOW"
export const ENABLE_TAB             = "ENABLE_TAB"
export const DISABLE_TAB           	= "DISABLE_TAB"
export const MAKE_COMMENT         	= "MAKE_COMMENT"
export const MAKING_COMMENT_SUCCESS = "MAKING_COMMENT_SUCCESS"
export const MAKING_COMMENT_ERROR   = "MAKING_COMMENT_ERROR"
export const START_SEEKING          = "START_SEEKING"
export const SEEKING_SUCCESS        = "SEEKING_SUCCESS"
export const SEEKING_FAILED         = "SEEKING_FAILED"
